# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/**
    - ios/**
    - test/**
  errors:
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore